# Определение стадий и задач
stages:
  - build

# Определение задачи для билда и пуша контейнера
build_and_push:
  stage: build
  script:
    # Билд нового контейнера
    - docker-compose up -d --build

    # Пуш контейнера в локальный Docker registry
    - docker run -d -p 5000:5000 --restart always --name registry registry:2
    - docker tag djangogirls_app localhost:5000/djangogirls_app
    - docker push localhost:5000/djangogirls_app
    - docker run -d -e ENV_DOCKER_REGISTRY_HOST=5.35.86.16 -e ENV_DOCKER_REGISTRY_PORT=5000 -p 8091:80 konradkleine/docker-registry-frontend:v2
