stages:
  - build
  - push
  - deploy

variables:
  CI_REGISTRY_IMAGE: "5.35.86.16/spirit/django"
  DEPLOY_SERVER: "root@31.129.97.232"
  DEPLOY_PATH: "/home/django"


build:
  stage: build
  script:
    - docker build -t djangogirls-nginx -f Dockerfile.nginx ./
    - docker build -t djangogirls-app -f Dockerfile.app ./
    - docker build -t djangogirls-db -f Dockerfile.db ./

push:
  stage: push
  script:
    - docker tag djangogirls-nginx localhost:5000/djangogirls-nginx
    - docker tag djangogirls-app localhost:5000/djangogirls-app
    - docker tag djangogirls-db localhost:5000/djangogirls-db
    - docker push localhost:5000/djangogirls-nginx 
    - docker push localhost:5000/djangogirls-app
    - docker push localhost:5000/djangogirls-db

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
  script:
    - scp docker-compose.production.yml $DEPLOY_SERVER:$DEPLOY_PATH/
    - ssh $DEPLOY_SERVER "cd /home/django && docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY && docker-compose -f docker-compose.production.yml pull && docker-compose -f docker-compose.production.yml up -d"
  only:
    - main
