stages:
  - build

variables:
  # Замените этот адрес на адрес вашего реестра, если $CI_REGISTRY_IMAGE не устанавливается автоматически
  CI_REGISTRY_IMAGE: "5.35.86.16/spirit/django"

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID ./

