version: "3.8"

services:
  nginx:
    image: $CI_REGISTRY_IMAGE/nginx:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID 
#    build:
#      context: .
#      dockerfile: Dockerfile.nginx
    ports:
      - "8081:80"
    depends_on:
      - app

  app:
    image: $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
    container_name: djangogirls-app
#    build:
#      context: .
#      dockerfile: Dockerfile.app
    stdin_open: true
    tty: true
    init: true
    environment:
      - POSTGRES_USER=djangogirls
      - POSTGRES_PASSWORD=djangogirls
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=djangogirls
    depends_on:
      - db
    #volumes:
      #- .:/var/www/app
   # ports:
   #   - "${APP_PORT:-8000}:8000"

  db:
    image: $CI_REGISTRY_IMAGE/db:$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
    container_name: djangogirls-db
#    build:
#      context: .
#      dockerfile: Dockerfile.db
    environment:
      POSTGRES_USER: djangogirls
      POSTGRES_PASSWORD: djangogirls
      POSTGRES_DB: djangogirls
    volumes:
      - pgdata:/var/lib/postgresql/data
   # ports:
   #   - "${DB_PORT:-5432}:5432"

volumes:
  pgdata:
