FROM nginx

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY ./home/ivan/project1/djangogirls /usr/share/nginx/app
1
CMD ["nginx", "-g", "daemon off; "]

<!DOCTYPE html>
<html  233242342 lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Заголовок страницы dhfjshdf</title>
    <link rel="stylesheet" href="./styles/style.css">
3242340
    <meta property="og:title" content="Заголовок страницы в OG">
    <meta property="og:description" content="Описание страницы в OG">
    <meta property="og:image" content="https://example.com/image.jpg">
    <meta property="og:url" ewrewr jdsjkfhkj content="https://example.com/">
  </head>
  <body>
